name: Publish Docker
on:
  push:
    branches:
      - ver/1.8.8
jobs:
  push:
    name: Push image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Escape branch name
        run: |
          ref="${github_ref////-}"
          echo "git_ref=$ref" >> $GITHUB_ENV
        env:
          github_ref: ${{ github.ref_name }}
      - name: Login to GH Registry
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Create build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/build.Dockerfile
          tags: ghcr.io/projectkig/kigpaper/kig-paper-builder:${{ env.git_ref }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Create HotSpot image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/projectkig/kigpaper/kig-paper:${{ env.git_ref }}
          build-args: |
            git_ref=${{ env.git_ref }}
      - name: Create J9 image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/j9.Dockerfile
          tags: ghcr.io/projectkig/kigpaper/kig-paper:${{ env.git_ref }}_j9
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            git_ref=${{ env.git_ref }}